In [2]:
import numpy as np

In [4]:
#reshape
test_matrix = [[1,2,3,4], [1,2,5,8]]
np.array(test_matrix).reshape(2,2,2)

array([[[1, 2],
        [3, 4]],

       [[1, 2],
        [5, 8]]])

In [3]:
#flatten()
test_matrix = [[[1,2,3,4], [1,2,5,8]], [[1,2,3,4], [1,2,5,8]]]
np.array(test_matrix).flatten()

array([1, 2, 3, 4, 1, 2, 5, 8, 1, 2, 3, 4, 1, 2, 5, 8])

In [5]:
#slicing
test_exmaple = np.array([
    [1, 2, 5,8], [1, 2, 5,8],[1, 2, 5,8],[1, 2, 5,8]], int)
test_exmaple[:2,:]

array([[1, 2, 5, 8],
       [1, 2, 5, 8]])

In [6]:
#arrange
np.arange(30).reshape(-1,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [7]:
#zeros
np.zeros(shape=(10,), dtype=np.int8) # 10 - zero vector 생성

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int8)

In [8]:
#zeros
np.zeros((2,5)) # 2 by 5 - zero matrix 생성

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [9]:
#ones
np.ones(shape=(10,), dtype=np.int8)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int8)

In [10]:
#ones
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [11]:
#random 생성
np.random.uniform(0,1,10).reshape(2,5)

array([[0.4608569 , 0.17706844, 0.80680738, 0.18477765, 0.74946517],
       [0.0885614 , 0.77654994, 0.50618361, 0.48203477, 0.30739112]])

In [12]:
#random 생성
np.random.normal(0,1,10).reshape(2,5)

array([[ 1.19022813,  1.40731555, -0.08225367, -0.04772039, -0.04835009],
       [ 0.20416983, -2.29313179, -0.79316033, -2.0181879 ,  1.49560274]])

In [13]:
    ---------------------------------------------- # operation
test_array = np.arange(1,11)
test_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
test_array.sum(dtype=np.float)

55.0

In [24]:
test_array = np.arange(1,13).reshape(3,4)
test_array.sum()

78

In [23]:
test_array.sum(axis=1)
test_array.sum(axis=0)

array([15, 18, 21, 24])

In [ ]:
----------------------------------------------------------------------------

In [18]:
---------------------------------------------#concatenate

a = np.array([1, 2, 3])
b = np.array([2, 3, 4])
np.vstack((a,b))

array([[1, 2, 3],
       [2, 3, 4]])

In [19]:
a = np.array([ [1], [2], [3]])
b = np.array([ [2], [3], [4]])
np.hstack((a,b))

array([[1, 2],
       [2, 3],
       [3, 4]])

In [20]:

a = np.array([[1, 2, 3]])
b = np.array([[2, 3, 4]])
np.concatenate( (a,b) ,axis=0)

array([[1, 2, 3],
       [2, 3, 4]])

In [21]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])

np.concatenate( (a,b.T) ,axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

In [ ]:
--------------------------------------------------------

In [29]:
#---------------------------------------#comparison

In [27]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
a>5

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [31]:
np.any(a>5), np.any(a<0)

(True, False)

In [32]:
np.all(a>5) , np.all(a < 10)

(False, True)

In [ ]:
#---------------------------------------#comparison operation

In [33]:
test_a = np.array([1, 3, 0], float)
test_b = np.array([5, 2, 1], float)
test_a > test_b

array([False,  True, False])

In [34]:
test_a == test_b

array([False, False, False])

In [35]:
(test_a > test_b).any()

True

In [37]:
a = np.array([1, 3, 0], float)
np.where(a > 0, 3, 2) # 조건에 맞으면 3으로 아니면 2로 바꿔서 넣기.

array([3, 3, 2])

In [38]:
a = np.arange(5, 15)
a

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [39]:
np.where(a>10)

(array([6, 7, 8, 9], dtype=int64),)

In [ ]:
# argmax,argmin 최대값과 최소값의 index위치를 리턴
a = np.array([1,2,4,5,8,78,23,3])
np.argmax(a) , np.argmin(a)

In [40]:
a=np.array([[1,2,4,7],[9,88,6,45],[9,76,3,4]])
np.argmax(a, axis=1) , np.argmin(a, axis=0)

(array([3, 1, 1], dtype=int64), array([0, 0, 2, 2], dtype=int64))

In [ ]:
# --------------------------------------------------------boolean index

In [41]:
test_array = np.array([1, 4, 0, 2, 3, 8, 9, 7], float)
test_array > 3

array([False,  True, False, False, False,  True,  True,  True])

In [42]:
test_array[test_array > 3]

array([4., 8., 9., 7.])

In [ ]:
#fancy index

In [43]:
a = np.array([2, 4, 6, 8], float)

In [44]:
a[a>4]

array([6., 8.])